language: cpp

compiler:
  - gcc

install:
  - sudo apt-get -y install libqt4-dev libqtwebkit-dev libglib2.0-dev libgtk2.0-dev libgdk-pixbuf2.0-dev libappindicator-dev

script:
  - ./build.linux.sh

env:
  global:
    - secure: "TbKqfr7dR1C5OSELNEhcj9qz0rSs1TftrV75v7HIM5+koUj8qFWTE74WRZ0Z7XF4+BNpuyGDr5gKNidRTGGtUzJK/2rCfeKupyRhq1S7jlnboLV68eHLMcFZ5YMEMvUxAgwKszPUbcVTkUDFGILTlTRu1fFd+KISVG8LxOEOIQA="

addons:
  coverity_scan:
    project:
      name: "abbat/ekstertera"
      description: "Build submitted via Travis CI"
    notification_email: antonbatenev@yandex.ru
    build_command_prepend: true
    build_command: ./build.linux.sh
    branch_pattern: master

branches:
  only:
    - master
